id = "kotlin"
name = "Kotlin"
version = "0.1.3"
schema_version = 1
authors = ["Vivek"]
description = "Kotlin language support."
repository = "https://github.com/itsvks19/kotlin-klyx"

[language_servers.kotlin-language-server]
name = "Kotlin Language Server"
language = "Kotlin"

[language_servers.kotlin-lsp]
name = "Kotlin LSP"
language = "Kotlin"
